### ISSUE TITLE
第４章で追加した Models の test が成功しない

### ISSUE THREAD

**Issue by sogaoh** [sogaoh/sam-book-sample#4]
[共通]
- 時刻の照合が成功しない -> コメントアウトで凌ぐ
    - `//assert.Equal(t, product.ReleaseDate.Format("2006-01-02T15:04:05Z"), result.ReleaseDate.Format("2006-01-02T15:04:05Z"))`
    - `//assert.Equal(t, expected.ReleaseDate, product.ReleaseDate)` でもダメなのはどうして？

[個別]
- (成功する) : TestProduct_GetProducts
```
❯ make go-test PACKAGE=models ARGS="--run TestProduct_GetProducts"
COMPOSE_PROJECT_NAME=sam-book-sample docker-compose -f docker-compose.yml run go-test ./scripts/go-test.sh 'models' '--run TestProduct_GetProducts'
Starting sam-book-sample_dynamodb-local_1 ... done
Wait for http://dynamodb-local:8000
--------------
Running go test.

START| Product_GetProducts
PASS | Product_GetProducts (0.14s)
PASS | sam-book-sample/models 0.157s
go test OK.
--------------
TEST DONE.
--------------
```

他は成功しない
- TestProduct_Create
```
❯ make go-test PACKAGE=models ARGS="--run TestProduct_Create"
COMPOSE_PROJECT_NAME=sam-book-sample docker-compose -f docker-compose.yml run go-test ./scripts/go-test.sh 'models' '--run TestProduct_Create'
Starting sam-book-sample_dynamodb-local_1 ... done
Wait for http://dynamodb-local:8000
--------------
Running go test.

START| Product_Create
FAIL | --- FAIL: TestProduct_Create (0.11s)
     |     product_test.go:39:
     |         	Error Trace:	product_test.go:39
     |         	Error:      	Received unexpected error:
     |         	            	dynamo: no item found
     |         	Test:       	TestProduct_Create
     |     product_test.go:41:
     |         	Error Trace:	product_test.go:41
     |         	Error:      	Not equal:
     |         	            	expected: "テスト製品"
     |         	            	actual  : ""
     |
     |         	            	Diff:
     |         	            	--- Expected
     |         	            	+++ Actual
     |         	            	@@ -1 +1 @@
     |         	            	-テスト製品
     |         	            	+
     |         	Test:       	TestProduct_Create
     |     product_test.go:42:
     |         	Error Trace:	product_test.go:42
     |         	Error:      	Not equal:
     |         	            	expected: 100
     |         	            	actual  : 0
     |         	Test:       	TestProduct_Create
FAIL | 	sam-book-sample/models	0.147s
--------------
go test FAILED.
--------------
RETURNCD: 1
make: *** [go-test] Error 1
```

- TestProduct_Update
```
❯ make go-test PACKAGE=models ARGS="--run TestProduct_Update"
COMPOSE_PROJECT_NAME=sam-book-sample docker-compose -f docker-compose.yml run go-test ./scripts/go-test.sh 'models' '--run TestProduct_Update'
Starting sam-book-sample_dynamodb-local_1 ... done
Wait for http://dynamodb-local:8000
--------------
Running go test.

START| Product_Update
FAIL | --- FAIL: TestProduct_Update (0.10s)
     |     product_test.go:69:
     |         	Error Trace:	product_test.go:69
     |         	Error:      	Received unexpected error:
     |         	            	ConditionalCheckFailedException: The conditional request failed
     |         	            		status code: 400, request id: 98b0dd54-ace8-419b-9044-e0772ea7b639
     |         	            	sam-book-sample/models.updateEntityToDynamo
     |         	            		/go/src/sam-book-sample/models/dynamo_model_mapper.go:131
     |         	            	sam-book-sample/models.(*Product).UpdateDynamoRecord
     |         	            		/go/src/sam-book-sample/models/product.go:48
     |         	            	sam-book-sample/models.putEntityToDynamo
     |         	            		/go/src/sam-book-sample/models/dynamo_model_mapper.go:159
     |         	            	sam-book-sample/models.(*Product).PutToDynamo
     |         	            		/go/src/sam-book-sample/models/product.go:40
     |         	            	sam-book-sample/models.(*Product).Update
     |         	            		/go/src/sam-book-sample/models/product.go:85
     |         	            	sam-book-sample/models.TestProduct_Update
     |         	            		/go/src/sam-book-sample/models/product_test.go:68
     |         	            	testing.tRunner
     |         	            		/usr/local/go/src/testing/testing.go:827
     |         	            	runtime.goexit
     |         	            		/usr/local/go/src/runtime/asm_amd64.s:1333
     |         	Test:       	TestProduct_Update
     |     product_test.go:79:
     |         	Error Trace:	product_test.go:79
     |         	Error:      	Not equal:
     |         	            	expected: "テスト製品（更新）"
     |         	            	actual  : "テスト製品"
     |
     |         	            	Diff:
     |         	            	--- Expected
     |         	            	+++ Actual
     |         	            	@@ -1 +1 @@
     |         	            	-テスト製品（更新）
     |         	            	+テスト製品
     |         	Test:       	TestProduct_Update
     |     product_test.go:80:
     |         	Error Trace:	product_test.go:80
     |         	Error:      	Not equal:
     |         	            	expected: 200
     |         	            	actual  : 100
     |         	Test:       	TestProduct_Update
FAIL | 	sam-book-sample/models	0.130s
--------------
go test FAILED.
--------------
RETURNCD: 1
make: *** [go-test] Error 1
```

- TestProduct_GetProductByID
```
❯ make go-test PACKAGE=models ARGS="--run TestProduct_GetProductByID"
COMPOSE_PROJECT_NAME=sam-book-sample docker-compose -f docker-compose.yml run go-test ./scripts/go-test.sh 'models' '--run TestProduct_GetProductByID'
Starting sam-book-sample_dynamodb-local_1 ... done
Wait for http://dynamodb-local:8000
--------------
Running go test.

START| Product_GetProductByID
FAIL | --- FAIL: TestProduct_GetProductByID (0.06s)
     | panic: runtime error: invalid memory address or nil pointer dereference [recovered]
     | 	panic: runtime error: invalid memory address or nil pointer dereference
     | [signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x7e33f6]
     | goroutine 20 [running]:
     | testing.tRunner.func1(0xc000076300)
     | 	/usr/local/go/src/testing/testing.go:792 +0x387
     | panic(0x84bba0, 0xc59bd0)
     | 	/usr/local/go/src/runtime/panic.go:513 +0x1b9
     | sam-book-sample/models.TestProduct_GetProductByID(0xc000076300)
     | 	/go/src/sam-book-sample/models/product_test.go:149 +0x126
     | testing.tRunner(0xc000076300, 0x8e7ee8)
     | 	/usr/local/go/src/testing/testing.go:827 +0xbf
     | created by testing.(*T).Run
     | 	/usr/local/go/src/testing/testing.go:878 +0x35c
FAIL | 	sam-book-sample/models	0.084s
--------------
go test FAILED.
--------------
RETURNCD: 1
make: *** [go-test] Error 1
```

- TestProduct_DeleteProduct
```
❯ make go-test PACKAGE=models ARGS="--run TestProduct_DeleteProduct"
COMPOSE_PROJECT_NAME=sam-book-sample docker-compose -f docker-compose.yml run go-test ./scripts/go-test.sh 'models' '--run TestProduct_DeleteProduct'
Starting sam-book-sample_dynamodb-local_1 ... done
Wait for http://dynamodb-local:8000
--------------
Running go test.

START| Product_DeleteProduct
FAIL | --- FAIL: TestProduct_DeleteProduct (0.08s)
     |     product_test.go:175:
     |         	Error Trace:	product_test.go:175
     |         	Error:      	Not equal:
     |         	            	expected: *errors.errorString(&errors.errorString{s:"dynamo: no item found"})
     |         	            	actual  : <nil>(<nil>)
     |         	Test:       	TestProduct_DeleteProduct
FAIL | 	sam-book-sample/models	0.110s
--------------
go test FAILED.
--------------
RETURNCD: 1
make: *** [go-test] Error 1
```

**Comment by memememomo** [comment]
`dynamo: no item found` というエラーが出ているので、Createメソッドでレコードが正常に作られていないようです。それ由来で  `時刻の照合が成功しない` のではないかと思います。

本では以下のように、 `dynamo:"Name"` をシングルクォートで囲っているのですが、

```
type Product struct {
        BaseModel
        Name        string    ‘dynamo:"Name"‘
        Price       int       ‘dynamo:"Price"‘
        ReleaseDate time.Time ‘dynamo:"ReleaseDate"‘
}
```

以下のように、バッククォート (`) で囲うようにしてみてください 🙇 

```
type Product struct {
        BaseModel
        Name        string    `dynamo:"Name"`
        Price       int       `dynamo:"Price"`
        ReleaseDate time.Time `dynamo:"ReleaseDate"`
}
```

**Comment by sogaoh** [comment]
@memememomo コメントありがとうございます。

> 以下のように、バッククォート (`) で囲うようにしてみてください 🙇

確認しましたが、その点は大丈夫そうです。。
https://github.com/sogaoh/sam-book-sample/blob/practice-sogaoh/models/product.go#L13-L18

**Comment by memememomo** [comment]
https://github.com/sogaoh/sam-book-sample/blob/practice-sogaoh/models/product.go#L36
こちらで `getPK(p)` となっているところを `getSK(p)` に変更すると良さそうです 👀

**Comment by sogaoh** [comment]
ありがとうございます 🙇🙇🙇🙇🙇
１文字の間違い、見つけていただいて本当に感謝です。 🥇  

```

❯ make go-test PACKAGE=models ARGS="--run TestProduct_Create"
COMPOSE_PROJECT_NAME=sam-book-sample docker-compose -f docker-compose.yml run go-test ./scripts/go-test.sh 'models' '--run TestProduct_Create'
Starting sam-book-sample_dynamodb-local_1 ... done
Wait for http://dynamodb-local:8000
--------------
Running go test.

START| Product_Create
PASS | Product_Create (0.24s)
PASS | sam-book-sample/models 0.257s
go test OK.
--------------
TEST DONE.
--------------

~/src/.../sam-book-sample practice-sogaoh* 32s


❯ make go-test PACKAGE=models ARGS="--run TestProduct_Update"
COMPOSE_PROJECT_NAME=sam-book-sample docker-compose -f docker-compose.yml run go-test ./scripts/go-test.sh 'models' '--run TestProduct_Update'
Starting sam-book-sample_dynamodb-local_1 ... done
Wait for http://dynamodb-local:8000
--------------
Running go test.

START| Product_Update
PASS | Product_Update (0.17s)
PASS | sam-book-sample/models 0.198s
go test OK.
--------------
TEST DONE.
--------------

~/src/.../sam-book-sample practice-sogaoh* 32s


❯ make go-test PACKAGE=models ARGS="--run TestProduct_GetProducts"
COMPOSE_PROJECT_NAME=sam-book-sample docker-compose -f docker-compose.yml run go-test ./scripts/go-test.sh 'models' '--run TestProduct_GetProducts'
Starting sam-book-sample_dynamodb-local_1 ... done
Wait for http://dynamodb-local:8000
--------------
Running go test.

START| Product_GetProducts
PASS | Product_GetProducts (0.14s)
PASS | sam-book-sample/models 0.162s
go test OK.
--------------
TEST DONE.
--------------

~/src/.../sam-book-sample practice-sogaoh* 31s


❯ make go-test PACKAGE=models ARGS="--run TestProduct_GetProductByID"
COMPOSE_PROJECT_NAME=sam-book-sample docker-compose -f docker-compose.yml run go-test ./scripts/go-test.sh 'models' '--run TestProduct_GetProductByID'
Starting sam-book-sample_dynamodb-local_1 ... done
Wait for http://dynamodb-local:8000
--------------
Running go test.

START| Product_GetProductByID
PASS | Product_GetProductByID (0.13s)
PASS | sam-book-sample/models 0.140s
go test OK.
--------------
TEST DONE.
--------------

~/src/.../sam-book-sample practice-sogaoh* 29s


❯ make go-test PACKAGE=models ARGS="--run TestProduct_DeleteProduct"
COMPOSE_PROJECT_NAME=sam-book-sample docker-compose -f docker-compose.yml run go-test ./scripts/go-test.sh 'models' '--run TestProduct_DeleteProduct'
Starting sam-book-sample_dynamodb-local_1 ... done
Wait for http://dynamodb-local:8000
--------------
Running go test.

START| Product_DeleteProduct
PASS | Product_DeleteProduct (0.15s)
PASS | sam-book-sample/models 0.163s
go test OK.
--------------
TEST DONE.
--------------

~/src/.../sam-book-sample practice-sogaoh* 30s
```
